### PR TITLE
Classification, Infobox parsing, BFS

### PR DESCRIPTION
**Pull request by mikewheel**

### CODE REVIEW

**Comment by mikewheel** [comment]
Merge commit included changes detailed in #5 . TL;DR moved files into `test`, moved table creation code to `data_stores/sqlite`

**Comment by mikewheel** [comment]
@jaymatthewsherman I couldn't evaluate the code because I hit a bug in the SQLite table creation script. Can you look over the merge and make sure it's mostly kosher?

**Comment by mikewheel** [comment]
```
Traceback (most recent call last):
  File "/home/michael/Documents/ds4300/final_project/virtualenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2646, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'byte:id:title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michael/Documents/ds4300/final_project/data_stores/sqlite/__init__.py", line 25, in <module>
    indices_values = indices["byte:id:title"]
  File "/home/michael/Documents/ds4300/final_project/virtualenv/lib/python3.8/site-packages/pandas/core/frame.py", line 2800, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/michael/Documents/ds4300/final_project/virtualenv/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 2648, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 111, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1619, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1627, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'byte:id:title'
```

**Review by jaymatthewsherman — APPROVED** [review]
Had to remove some duplicate code, but otherwise top notch

**Pull request merged**
